### ISSUE TITLE
Unit Test Diagram

### ISSUE THREAD

**Issue by sohilpandya** [foundersandcoders/learn-qunit#1]
@skibinska might be worth you adding this diagram to explain that this is the lowest and the **most important** level of testing that can be done and we'll be touch the other sections of testing throughout the course. 

![](https://media.licdn.com/mpr/mpr/p/8/005/099/219/08c5a55.jpg)

**Comment by skibinska** [comment]
cool @sohilpandya  :+1:  I will add it
